name: Rachel Gold

## Conversion
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

include:
  - _stylesheets
  - _javascript

sass:
  load_paths:
    - assets/_scss

# Custom site configuration
lang: en

defaults:
  - scope:
      path: ""
    values:
      lang: "en"

exclude:
  - Gemfile
  - Gemfile.lock
  - Procfile
  - README.md
  - Rakefile
  - bin
  - config.rb
  - gems
  - hidden-posts
  - script
  - vendor
  - mise.toml
  - package.json
